# Generated by Django 5.1.7 on 2025-03-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DermaCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='derma_images/')),
                ('description', models.TextField()),
                ('diagnosis', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
