# Generated by Django 5.1.7 on 2025-03-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dermacase',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='dermacase',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dermacase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
